version: 1.0.{build}
branches:
  only:
  - dev/appveyor-windows
skip_tags: true
image: Visual Studio 2017
install:
- cmd: >-
    cd Group-Video\OpenLive-Windows

    set SDKVersion=3_0_0

    set SDKFolderVersion=3.0.0

    set ProjName=OpenLive
build_script:
- cmd: >-
    call build_appveyor_release.bat %SDKVersion% %SDKFolderVersion% x86 %ProjName%

    call build_appveyor_release.bat %SDKVersion% %SDKFolderVersion% x64 %ProjName%

    7z a -tzip -r OpenLive_Win_v%SDKFolderVersion%.zip %ProjName%_Win_v%SDKFolderVersion%
artifacts:
- path:OpenLive-Windows\OpenVideoCall_Win_v*.zip
  name: OpenLive-Windows