# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master
- dev/*

variables:
  iOSRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_iOS_v3_0_1_FULL.zip?_ga=2.39937186.1429354637.1591107319-5559409.1503304822'
  MacRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Mac_v3_0_1_FULL.zip?_ga=2.49505318.1429354637.1591107319-5559409.1503304822'
  WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x86)_v3_0_0_2_FULL.zip'
  WindowsRTCSDKX64: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x64)_v3_0_0_2_FULL.zip'

jobs:
- template: 'OpenLive-Android/open-live-template.yml'
  parameters:
    project: 'OpenLive-Android'
    name: 'OpenLive_Android'

- template: cicd/templates/build-ios.yml
  parameters:
    displayName: 'iOSSwiftOpenLive'
    workingDirectory: 'OpenLive-iOS'
    scheme: 'OpenLive'
    sdkurl: $(iOSRTCSDK)

- template: cicd/templates/build-ios.yml
  parameters:
    displayName: 'iOSOCOpenLive'
    workingDirectory: 'OpenLive-iOS-Objective-C'
    scheme: 'OpenLive'
    sdkurl: $(iOSRTCSDK)

- template: cicd/templates/build-mac.yml
  parameters:
    displayName: 'MacSwiftOpenLive'
    workingDirectory: 'OpenLive-macOS'
    scheme: 'OpenLive'
    sdkurl: $(MacRTCSDK)

- template: cicd/templates/build-mac.yml
  parameters:
    displayName: 'MacOCOpenLive'
    workingDirectory: 'OpenLive-macOS-Objective-C'
    scheme: 'OpenLive'
    sdkurl: $(MacRTCSDK)

#Windows MFC demo
  - template: cicd/templates/build-Windows.yml
    parameters:
      displayName: 'WindowsOpenLiveMFC'
      workingDirectory: 'OpenLive-Windows-MFC'
      scheme: 'OpenLive-Windows-MFC'
      sdkurl: $(WindowsRTCSDK)
      solutionName: 'OpenLive.sln'
      Machine: 'win32'
      architecture: 'x86'
      ReleasePath: 'Release'

 - template: cicd/templates/build-Windows.yml
    parameters:
      displayName: 'WindowsOpenLiveMFC64'
      workingDirectory: 'OpenLive-Windows-MFC'
      scheme: 'OpenLive-Windows-MFC'
      sdkurl: $(WindowsRTCSDK)
      solutionName: 'OpenLive.sln'
      Machine: 'x64'
      architecture: 'x64'
      ReleasePath: 'x64/Release'
#Windows QT
  - template: cicd/templates/build-Windows-QT.yml
    parameters:
      displayName: 'WindowsOpenLive'
      workingDirectory: 'OpenLive-Windows'
      scheme: 'OpenLive-Windows'
      sdkurl: $(WindowsRTCSDK)
      architecture: 'x86'
      ReleasePath: 'Release'
      QtDir: 'C:\Qt5.10.1\msvc2017'
 - template: cicd/templates/build-Windows-QT.yml
    parameters:
      displayName: 'WindowsOpenLive64'
      workingDirectory: 'OpenLive-Windows'
      scheme: 'OpenLive-Windows'
      sdkurl: $(WindowsRTCSDK)
      architecture: 'x64'
      ReleasePath: 'Release'
      QtDir: 'C:\Qt5.10.1\msvc2017'