# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master
- dev/*

variables:
  iOSRTCSDK: 'https://release.agoralab.co/disk/v3.0.0_IOS_SO/AgoraSDK/iOS/Agora_Native_SDK_for_iOS_v3_0_0_FULL_20191119_1479.zip'
  MacRTCSDK: 'https://release.agoralab.co/disk/v3.0.0_IOS_SO/AgoraSDK/Mac/Agora_Native_SDK_for_Mac_v3_0_0_FULL_20191119_822.zip'

jobs:
- template: 'OpenLive-Android/open-live-template.yml'
  parameters:
    project: 'OpenLive-Android'
    name: 'OpenLive_Android'

- template: cicd/templates/build-ios.yml
  parameters:
    displayName: 'iOSSwiftOpenLive'
    workingDirectory: 'OpenLive-iOS'
    scheme: 'OpenLive'
    sdkurl: $(iOSRTCSDK)

- template: cicd/templates/build-ios.yml
  parameters:
    displayName: 'iOSOCOpenLive'
    workingDirectory: 'OpenLive-iOS-Objective-C'
    scheme: 'OpenLive'
    sdkurl: $(iOSRTCSDK)

- template: cicd/templates/build-ios.yml
  parameters:
    displayName: 'MacSwiftOpenLive'
    workingDirectory: 'OpenLive-macOS'
    scheme: 'OpenLive'
    sdkurl: $(MacRTCSDK)

- template: cicd/templates/build-ios.yml
  parameters:
    displayName: 'MacOCOpenLive'
    workingDirectory: 'OpenLive-macOS-Objective-C'
    scheme: 'OpenLive'
    sdkurl: $(MacRTCSDK)
